apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uk0fge51v-python 
  janus-idp.io/tekton: uk0fge51v-python
  backstage.io/kubernetes-id: uk0fge51v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uk0fge51v-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml